### ISSUE TITLE
Physics tied to framerate

### ISSUE THREAD

**Issue by braboware** [KenneyNL/Starter-Kit-FPS#4]
This can be seen by comparing the gun knockback with different settings. Knockback moves the player a shorter distance when vsync is off and the game is allowed to reach higher frame rates and knockback moves the player a further distance when max_fps is set lower.

At a very low max_fps like 10, looking around goes crazy and is uncontrollable

**Comment by KenneyNL** [comment]
These issues should now be fixed, thanks for reporting!
