### ISSUE TITLE
Model with overlapping vertices Z-Fighting

### ISSUE THREAD

**Issue by fuzzdistor** [KenneyNL/Starter-Kit-FPS#6]
There is noticeable z-fighting on the enemy models when at a distance

Example:
![Screenshot of the model z-fighting](https://i.imgur.com/XsgnNd9.png)

The model has a lot of overlapping vertices. When applying `merge by distance` on blender this is the output:
![Overlapping vertices merged by `merge by distance` option on blender](https://i.imgur.com/74fKTvU.png)

I'm not a modeler, so I don't know if that overlap is intended, but merging the vertices of the faceplate fixes the issue.
![Merging the faceplate](https://i.imgur.com/85ww2FR.png)
![Vertices merged](https://i.imgur.com/KBpsE5q.png)

With new model:
![Screenshot of enemy from afar](https://i.imgur.com/mZsaah7.png)

**Comment by KenneyNL** [comment]
Thanks for letting me know, I've fixed the model files!

**Comment by fuzzdistor** [comment]
Thanks for this starter kit! It is incredibly valuable <3
